apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-rollout
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-bg-app
  template:
    metadata:
      labels:
        app: flask-bg-app
    spec:
      containers:
        - name: flask-simple
          image: docker.io/nightmar39/flask-bg-app:e03addb
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP