apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- service.yaml
images:
- name: docker.io/nightmar39/flask-bg-app
  newName: docker.io/salesdemosa/flask-cz
  newTag: b3f46f3
- name: quay.io/codefresh_sa/color-service
  newName: docker.io/salesdemosa/flask-cz
  newTag: f99708f
